<?php

/**
 * @file Word Of The Hour module
 * Responsible for Word Of The Hour Drupal hook implementations.
 */

/**
 * Implements Drupal's hook_menu().
 */
function wordofthehour_menu() {
  $items = array();

  $items['admin/settings/wordofthehour'] = array(
    'title' => 'Word Of The Hour Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wordofthehour_settings'),
    'access arguments' => array('administer Word Of The Hour'),
    'description' => t('Word Of The Hour settings'),
    'file' => 'wordofthehour.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  $items['wordofthehour'] = array(
    'title' => 'Word of the Hour',
    'page callback' => 'wordofthehour_page',
    'access callback' => TRUE,
    'description' => t('Get word of the hour'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements Drupal's hook_perm().
 */
function wordofthehour_permissions() {
  return array(
    'administer wordofthehour' => array(
      'title' => t('Administer Word Of The Hour settings'),
    ),
  );
}

/**
 * Implements hook_theme
 */
function wordofthehour_theme() {
   return array(
    'wordofthehour' => array(
      'template' =>  'tpls/wordofthehour',
      'variables' => array(
        'word' => NULL,
        'definition' => NULL,
      ),
    ),
  );
}

function wordofthehour_cron() {
  module_load_include('inc', 'wordofthehour', 'wordofthehour.db');
  module_load_include('inc', 'wordofthehour', 'wordofthehour.twitter');

  for ($i = 1; $i <= 3; $i++) {
    $word = wordofthehour_get_random_word();
    $definition = wordofthehour_get_definition_from_api($word);
    wordofthehour_store_definition($word, $definition);
  }
  $post_time = variable_get('wordofthehour_last_tweet', 10);
  if ($post_time < time() - 3600) {
    $random_def = $word . ": " . $definition;
    post_tweet(strip_tags($random_def));
    variable_set('wordofthehour_last_tweet', time());
    variable_set('wordofthehour_word', $word);
    variable_set('wordofthehour_definition', $definition);

    $date = date('m/d/Y', $post_time);
    watchdog('post-time', var_export($date, TRUE));
    wordofthehour_set_word_as_posted($word);
  }
}

function wordofthehour_get_definition_from_api($word) {
  $urlbase = "http://www.dictionaryapi.com/api/v1/references/collegiate/xml/";
  $apikey = "b8c6c7cd-c445-43d2-bf4d-dfed4b1ba55f";

  $url = $urlbase . urlencode(trim($word)) . '?key=' . $apikey;

  $response = drupal_http_request($url, array());

  $definition = wordofthehour_process_api_response($response);

  return $definition;
}

function wordofthehour_process_api_response($response) {
  $data = $response->data;

  $definition = trim(substr($data, strpos($data, ':') + 1));

  $ending = strpos($definition, '</dt>');

  $definition = substr($definition, 0, $ending);

  return $definition;
}

function wordofthehour_page() {
  module_load_include('inc', 'wordofthehour', 'wordofthehour.db');

  $word = variable_get('wordofthehour_word', 'hands down');
  ;
  $definition = variable_get('wordofthehour_definition', 'easily');

  return theme('wordofthehour', array(
    'word' =>$word,
    'definition' => $definition,
  ));
}
